title: that aboutness
email: nichol.alexander@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Things are about other things.  This is the thing about those first things.  Sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nicholalexander
github_username:  nicholalexander

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-press

permalink: pretty

tag_page_layout: tag_page
tag_page_dir: tag

sass:
    style: compressed
